#!/usr/bin/env python3
"""Re-generate ~/Vault/CryoDAQ/_meta/source map.md from current vault state.

Usage: python3 build_source_map.py
"""

import os, re
from collections import defaultdict
from pathlib import Path

VAULT = Path.home() / "Vault" / "CryoDAQ"
OUT = VAULT / "_meta" / "source map.md"

LINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|[^\]]*)?\]\]")
FRONT_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def main() -> None:
    note_paths: dict[str, Path] = {}
    note_meta: dict[str, dict[str, str]] = {}
    links_in: dict[str, set[str]] = defaultdict(set)
    links_out: dict[str, set[str]] = defaultdict(set)

    for full in sorted(VAULT.rglob("*.md")):
        rel = str(full.relative_to(VAULT))[:-3]
        note_paths[rel] = full
        content = full.read_text(encoding="utf-8")
        m = FRONT_RE.match(content)
        front: dict[str, str] = {}
        if m:
            for line in m.group(1).split("\n"):
                if ":" in line:
                    k, _, v = line.partition(":")
                    front[k.strip()] = v.strip()
        note_meta[rel] = front
        for lm in LINK_RE.finditer(content):
            target = lm.group(1).strip()
            links_out[rel].add(target)
            if target != rel:
                links_in[target].add(rel)

    rows: list[tuple[str, str, str, int, int]] = []
    for rel in sorted(note_paths):
        f = note_meta.get(rel, {})
        rows.append((
            rel,
            f.get("source", "—"),
            f.get("last_synced", "—"),
            len(links_in.get(rel, set())),
            len(links_out.get(rel, set())),
        ))

    groups: dict[str, list[tuple[str, str, str, int, int]]] = defaultdict(list)
    for r in rows:
        folder = r[0].split("/")[0]
        groups[folder].append(r)

    out_lines = [
        "---",
        "source: Phase 4 cross-link sweep — regenerated by build_source_map.py",
        "last_synced: regenerated-on-run",
        "status: generated",
        "---",
        "",
        "# Source map",
        "",
        "Every vault note with declared sources, last sync date, and",
        "link-graph degree. Re-run `build_source_map.py` after any",
        "structural change.",
        "",
        "## Map",
        "",
    ]
    for folder in sorted(groups):
        out_lines.append(f"### `{folder}/`")
        out_lines.append("")
        out_lines.append("| Note | Source | Last synced | In | Out |")
        out_lines.append("|---|---|---|---|---|")
        for rel, src, sync, inb, outb in sorted(groups[folder]):
            short_src = src if len(src) < 90 else src[:87] + "..."
            # Plain wikilink (no alias) so table-pipe escape is unnecessary
            out_lines.append(f"| [[{rel}]] | {short_src} | {sync} | {inb} | {outb} |")
        out_lines.append("")

    out_lines += [
        "## Counts",
        "",
        f"- Total notes: **{len(rows)}**",
        f"- Total inbound links recorded: **{sum(r[3] for r in rows)}**",
        f"- Total outbound links recorded: **{sum(r[4] for r in rows)}**",
        f"- Notes with zero inbound: **{sum(1 for r in rows if r[3] == 0)}**",
        "",
    ]

    OUT.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
